version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run serve
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - ./.env.development
